name: CI

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup node in order to test in action
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Check for successful build
              run: yarn run build

            - name: Run tests
              run: npm run test:ci | tee ./coverage.txt && exit ${PIPESTATUS[0]}

            - name: Jest Coverage Comment
              id: coverageComment
              uses: MishaKav/jest-coverage-comment@main
              with:
                  title: Jest Test Coverage
                  summary-title: Summary
                  badge-title: Coverage
                  hide-comment: true
                  coverage-summary-path: ./coverage/coverage-summary.json
                  coverage-path: ./coverage.txt
                  junitxml-path: ./coverage/junit.xml

            - name: Create the badge
              if: github.ref == 'refs/heads/main'
              uses: schneegans/dynamic-badges-action@v1.6.0
              with:
                  auth: ${{ secrets.COVERAGE_BADGE_GIST_TOKEN }}
                  gistID: 54b0c842747fa6be3cd6d344631a1651
                  filename: jest-coverage-comment__main.json
                  label: Coverage
                  message: ${{ steps.coverageComment.outputs.coverage }}%
                  color: ${{ steps.coverageComment.outputs.color }}
                  namedLogo: typescript

            # Will add work here to build the docker container and deploy that
            # container to Cloud Run, need to sort out containerization for that though
