name: CI

on:
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test:
        permissions:
            contents: 'read'
            id-token: 'write'

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup node in order to test in action
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Check for successful build
              run: yarn run build

            - name: Run tests
              run: npm run test:ci | tee ./coverage.txt && exit ${PIPESTATUS[0]}

            - name: Jest Coverage Comment
              id: coverageComment
              uses: MishaKav/jest-coverage-comment@main
              with:
                  title: Jest Test Coverage
                  summary-title: Summary
                  badge-title: Coverage
                  coverage-summary-path: ./coverage/coverage-summary.json
                  coverage-path: ./coverage.txt
                  junitxml-path: ./coverage/junit.xml
